name: start1
on: push

jobs: 
  build:
    name: Setting up
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: download sa 
        run: wget https://drive.google.com/uc?export=download&id=1BwVlfTKvaWyZYVOhimd1ynWbGIiyCGFT
      - name: unzip sa
        run: unzip accounts.zip .
      - name: show files
        run: ls ./accounts
