name: start1
on: push

jobs: 
  build:
    name: Setting up
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: download sa 
        run: wget https://github.com/AlphaKaskar/test/raw/main/accounts.zip
      - name: unzip sa
        run: unzip accounts.zip .
      - name: show files
        run: ls ./accounts
